---
title: "Workflows developed to process pollen data to estimate components of ecosystem change"
author: 
 - "Alistair Seddon"
 - "Ondřej Mottl" 
format: 
  revealjs:
    theme: moon
    incremental: true 
---

## PAGES Planetary Boundaries Working Group
-	Holocene variability is a key component of planetary boundaries concept
-	Focus on temporal dynamics/ safe operating spaces
-**"To meet the challenge of maintaining the Holocene state, we propose a framework based on 'planetary boundaries'. These boundaries define the safe operating space for humanity with respect to the Earth system and are associated with the planet's biophysical subsystems or processes."** Steffen et al. 2009 

---
-	How can we use palaeoecological (and related fields) data to address the planetary boundaries concept?
<!-- Add figure: Fig_Dearing_regional_operating_spaces.jpeg -->
---

## Example from pollen data
- Focus on temporal dynamics
-	We need a metric (or series of metrics that can reflect something related to the planetary boundary)
-	We need a method for describing the variability (e.g. using a generalised additive model)
-	If we are talking global planetary boundaries, we need to look at multiple records, so need a reproducible method to show how to do this.

---

## Diversity metrics 
-	Richness, evenness etc., can be estimated using Hill Numbers
-	One component of 'Ecosystem Condition' (see, e.g. Dearing et al. 2014)
-	Other metrics are available!
<!-- Add figure: Fig_Dearing_regional_operating_spaces.jpeg -->

---

## GAMs
-	Statistical model to show non-linear trends through time
-	Gavin Simpson has done the groundwork to transfer this method to palaeoecological data (Simpson 2018, Presentation on Wednesday, 11-11.15)
-	Models a trend (e.g. diversity against time) using a series of basis functions, allowing non-linear trends to be fit to data
-	‘Generalised’ framework means it is highly flexible, used on multiple data types
-	Note that it doesn’t necessarily tell us where we should draw the boundary, but it does give us a statistically robust description of the variability which we can then use to make informed decisions
<!-- add figure: Fig_simpson_gams.jpeg -->
---

## Reproducible workflows
-	If integrating across multiple sites then it is important to have standardized data that are comparable
-	In pollen this means- same depositional environment, same age-depth models, same levels of taxonomic harmonisation, (same/ similar temporal resolution), comparable temporal ranges etc.
-	We have been developing reproducible workflows for pollen data in the HOPE project, we will show an example of this today (see Ondrej's poster)

<!-- add figure: FossilPoll -->
---

## Example: Global changes in rates of vegetation change
<!-- add figure: Fi_RoC.jpeg -->
---

## Aims of this practical exercise
1.	Give an example data preparation and analysis of one metric related to the Biodiversity Planetary Boundary from a set of pollen counts from **Lingua d'Oca** (ID = 52162) record by Feredico Di Rita.
2.	Give hands-on practice of applying the code to other examples (e.g. downloaded from Neotoma)
3.	Stimulate some discussion points related to the types of metrics/ standardization procedures that are relevant for your data and for the Planetary Boundaries' concepts

---

## Practical exercise

Go to bit.ly/INQUA2023-PBW

---

## RoC

---

## Wrap up
-	Used this one  example of how to process the pollen data in standardized methodology
-	See the whole workflow which enables you to do this on Neotoma and other datasets (FossilPol).
-	Interpretation of results in relation to the Planetary Boundaries would be open ended, and is the focus of the group and for discussion here.

---

## Discussion points
- Here we focused on temporal dynamics, but how can we get from response to control variables?
-	What other metrics/ ecosystem components could be used on pollen data? What about other proxy types
-	What would be the challenges of doing large syntheses in the context of the planetary boundaries for your data types?
<!-- Add figure: Fig-response_control_variables.jpeg -->

